module.exports = {
  apps: [{
    name: "gecko-v2",
    script: "npx",
    args: "tsx src/index.ts",
    cwd: __dirname,
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: "500M",
    env: {
      NODE_ENV: "production",
      STARTING_CAPITAL: "5000",
      BROKER_ID: "paper",
      LIVE_TRADING: "false",
      ENABLE_NET_NET: "true",
      ENABLE_SPINOFF: "true",
      ENABLE_PEAD: "false",
      ENABLE_REG_SHO: "true",
      LOG_LEVEL: "info",
    },
    log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    error_file: "logs/error.log",
    out_file: "logs/out.log",
    merge_logs: true,
  }],
};
